### PR TITLE
test: use recommended nunit setup

### LINKED ISSUE #188: Tests are not being run.
**Describe the bug**
Tests are not being run 

**To Reproduce**

With a fresh install of VS2022, without any extensions try:

Running tests from the Test Explorer in VS2022.

or

From Command line:
```powershell
msbuild /t:restore
msbuild .\test\net
vstest.console .\test\net\bin\Debug\net472\MvvmDialogs.Test.dll
```

The result is:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test is available in Q:\Code\Library\mvvm-dialogs\.\test\net\bin\Debug\net472\MvvmDialogs.Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

**Expected behavior**
Tests need to run successfully.

```
🚀  vstest.console .\test\net\bin\Debug\net472\MvvmDialogs.Test.dll
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.2.0.0: Test execution started
Running all tests in Q:\Code\Library\mvvm-dialogs\.\test\net\bin\Debug\net472\MvvmDialogs.Test.dll
   NUnit3TestExecutor discovered 33 of 33 NUnit test cases using Current Discovery mode, Non-Explicit run
  Passed Add [44 ms]
  Passed AddSameTwice [5 ms]
  Passed Clear [< 1 ms]
  Passed Get [< 1 ms]
  Passed LocateDialogTypeSuccessful("TestAssembly.DialogViewModel","TestAssembly.Dialog") [3 ms]
  Passed LocateDialogTypeSuccessful("TestAssembly.ViewModels.DialogViewModel","TestAssembly.Views.Dialog") [< 1 ms]
  Passed LocateDialogTypeSuccessful("TestAssembly.ViewModels.Module.DialogViewModel","TestAssembly.Views.Module.Dialog") [< 1 ms]
  Passed LocateDialogTypeSuccessful("TestAssembly.Module.ViewModels.DialogViewModel","TestAssembly.Module.Views.Dialog") [< 1 ms]
  Passed LocateDialogTypeUnsuccessful("TestAssembly.ModuleWithoutViewNamespace.ViewModel.DialogViewModel") [< 1 ms]
  Passed LocateDialogTypeUnsuccessful("TestAssembly.UnconventionalNamespace.DialogViewModel") [< 1 ms]
  Passed ToDialog [9 ms]
  Passed ToSettings [< 1 ms]
  Passed NativeDialogSettingsParity [5 ms]
  Passed NativeDialogSettingsParity [4 ms]
  Passed Show [417 ms]
  Passed ToDialog [5 ms]
  Passed ToSettings [< 1 ms]
  Passed NativeDialogSettingsParity [< 1 ms]
  Passed ToDialog [1 ms]
  Passed ToSettings [< 1 ms]
  Passed NativeDialogSettingsParity [< 1 ms]
  Passed RegisterFrameworkElementUsingAttachedProperty [296 ms]
  Passed RegisterLoadedView [154 ms]
  Passed RegisterViewThatGetsLoaded [5 ms]
  Passed RegisterViewThatNeverGetsLoaded [4 ms]
  Passed RegisterWindowUsingAttachedProperty [< 1 ms]
  Passed UnregisterFrameworkElementUsingAttachedProperty [< 1 ms]
NUnit Adapter 4.2.0.0: Test execution complete
  Passed UnregisterLoadedView [1 ms]
  Passed UnregisterWhenClosingOwner [3 ms]
  Passed UnregisterWindowUsingAttachedProperty [1 ms]
  Passed EqualsOverride [< 1 ms]
  Passed GetHashCodeOverride [< 1 ms]
  Passed Source [< 1 ms]

Test Run Successful.
Total tests: 33
     Passed: 33
 Total time: 2.1878 Seconds
```

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Windows 11
 - .NET version: 4.7.2
 - Visual Studio version: 2022

### PR DESCRIPTION
**Pull request by virzak**
# Description

Follow the latest nunit installation [instructions](https://docs.nunit.org/articles/vs-test-adapter/Adapter-Installation.html#manually-adding-the-adapter-as-a-package-reference-to-your-test-projects)

Fixes #188 

# Checklist

- [x] I have squashed my commits into a single one with a message that aligns with the contributing guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Great work. As I've been using ReSharper, I haven't noticed that the tests doesn't get picked up by the VS test runner, but now with your changes I see that they do.

My only question is, why are we adding these dependencies only to `MvvmDialogs.Test`? Why aren't we adding these dependencies to all test projects?

**Comment by virzak** [comment]
I just placed them next to NUnit reference.

Come to think of it, I wonder if all the tests should be moved into a single project?
If these were purely tests, I'd say yes, but I think the point of these test projects is to use them as standalone samples of a test project, correct? Then I see why you'd want to add packages to the individual test projects.

**Comment by FantasticFiasco** [comment]
You're correct with your second statement. Keeping tests relating to the sample projects together with the sample projects makes more sense to me than bundling them all up in the same test project.

Regarding the added references. All sample projects reference the project `TestBaseClasses`, where we also find a NUnit reference. I think we should add the new references there as well.

**Comment by virzak** [comment]
> Regarding the added references. All sample projects reference the project `TestBaseClasses`, where we also find a NUnit reference. I think we should add the new references there as well.

`there` refers to sample projects or the project `TestBaseClasses`?

**Comment by FantasticFiasco** [comment]
Sorry for being ambiguous, `there` was referring to `TestBaseClasses`.

**Comment by virzak** [comment]
Done.

For some reason I thought that all test cases referenced the test/net project

**Comment by FantasticFiasco** [comment]
Thanks for noticing the issue, and thanks for the PR!

**Pull request merged**
