### PR TITLE
Code improvements 

### PR DESCRIPTION
**Pull request by MCCshreyas**
# Description

1. Used Expression body syntax for some methods which are simpler to understand. 
2. Used string interpolation rather than concatenation for better readability. 
3. Simplified `if` statements.
4. Used LINQ rather than `foreach`.
5. Used pattern matching.
6. Used using-declaration.
7. Used switch expression for simplicity.
8. Handled Null reference exception.

# Checklist

- [x] I have squashed my commits into a single one with a message that aligns with the contributing guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Thanks! I'll look into this PR tonight.

**Comment by FantasticFiasco** [comment]
Shoot, I didn't have time to look at this last night, but I'll look at it in the upcoming days. The changes looks to be really good, and rest assure, they will be counted towards your Hackoctober goal. Thank you so much for the contribution!

**Comment by MCCshreyas** [comment]
@FantasticFiasco Thanks. No Worries. Take your time! 😀

**Comment by FantasticFiasco** [comment]
I don't seem to have permissions to update your fork. Would you be able to update it as described in the [following documentation](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)? I would like to see that your previous PR fixed the failing interaction in this PR.

Thanks!

**Comment by MCCshreyas** [comment]
@FantasticFiasco if there is any thing that need to be done from my side, to merge this PR! Please let me know! Thanks!

**Comment by FantasticFiasco** [comment]
Everything seems to be really good, thank you for your contributions!

**Comment by MCCshreyas** [comment]
@FantasticFiasco Thanks for your reply. Can you please take [note ](https://hacktoberfest.digitalocean.com/hacktoberfest-update)of this, then mark my this PR (and other one ) as an accepted label, so it will consider as a contribution towards it?

**Comment by FantasticFiasco** [comment]
Didn't know you had to opt-in, thanks for the heads up!

I've added the topic to the repository, and since the PRs are merged they should count towards your goal. But just to be safe, I added the label as well.

**Pull request merged**
