### PR TITLE
Added the possibility to specify the FilterIndex in the FileDialogSet…

### PR DESCRIPTION
**Pull request by gigios**
…tings to select the correct filter used in the FileDialog (used in OpenFileDialogWrapper and SaveFileDialogWrapper)

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
I will help you with this PR when I get home from work.

Thank you for your contribution!

**Comment by gigios** [comment]
Thank you for the GitHub support ;)

**Comment by FantasticFiasco** [comment]
I think this PR is ready to be merged to `master` now. What remains is for you to squash all my commits into your first. Open a command prompt in the repository directory and type the following:

```
git pull
git rebase -i HEAD~6
```

You'll be presenter with the last 6 commits, what you should do is to squash my into yours by editing the text to look something like this.

```
pick fad5278 Added the possibility to specify the FilterIndex in the FileDialogSettings to select the correct filter used in the FileDialog (used in OpenFileDialogWrapper and SaveFileDialogWrapper)
s cc49f48 update changelog
s 2be4175 simplify ignore pattern
s 81c053e simplify xml comment link
s 9d5d33d rephrase changelog
s b5d0889 add credits
```

Save the file and exit the editor. Git will process your changes and will then present you with the option to edit the commit message. Please remove my messages, and leave with you own formatted like this:

```
# This is a combination of 6 commits.                                                                                 
# The first commit's message is:                                                                                      
feat: add filter index

Added the possibility to specify the FilterIndex in the FileDialogSettings to select the correct filter used in the FieDialog (used in OpenFileDialogWrapper and SaveFileDialogWrapper).

Closes #5
```

**Comment by gigios** [comment]
Ok! I'm using the Visual Studio GitHub integration for the first time.
I have also installed the git to use from the command prompt.
I'm able to execute the git pull command and the git rebase command that open the vim editor with, I think, your comments.
Now I'm blocked.
I don't know how to save the file, I have tried with :q and the file is closed with the message
"Successfully rebase and updated refs/heads/master"
If I try to execute git commit the message is:
"On branch master
Your branch is up-to-date with 'origin/master'."

My feeling is that the git has downloaded your changes but I'm not able to 'merge' these changes in my branch.

Sorry

**Comment by FantasticFiasco** [comment]
Don't apologize, if this was your first try you've done better than me at my first try.

The reason nothing changed is because you didn't save the file before closing it. I've updated my previous comment with more detailed instructions, give it a new try and report back to me.

Btw, I don't put you through this because I enjoy feeling your pain. It is because I would like you to take credit for your commit. If I squashed all commits into a single one, your name would be erased from the history, and I don't want that.

**Comment by gigios** [comment]
Ok! Thanks for the additional steps to do :D
I have seen some error messages during the git rebase command:
"error: cannot 'squash' without a previous commit"
I have followed the suggestion to use the git rebase --edit-todo and after the git rebase --continue
Probably the problem was that at the first test I have removed all the 'pick' commands, also on the first line.

I hope that all is well.
Thanks again for the support on Git

**Comment by FantasticFiasco** [comment]
I'll publish a beta NuGet tonight, if everything works as you expect, I'll officially release it.

Thanks for the contribution! And keep up the good work contributing to the open source community.

**Comment by FantasticFiasco** [comment]
I've release version `4.1.0-beta`. Can you try it out and see if it matches your expectations? If it does, I'll officially release it.

**Comment by gigios** [comment]
Ok! I have tried the source code and also the nuget package and all seems ok!
Good Job!

**Comment by FantasticFiasco** [comment]
Perfect, I'll release the official package tonight.

**Comment by FantasticFiasco** [comment]
4.1.0-beta became 4.1.1, it's now official on nuget.org

**Pull request merged**
