### PR TITLE
Updated Greetings workflow

### PR DESCRIPTION
**Pull request by MCCshreyas**
# Description
Changed to pull_request_target from pull_request.

Fixes # (issue)
This will fix the greetings workflow 

# Checklist

- [x] I have squashed my commits into a single one with a message that aligns with the contributing guidelines
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by MCCshreyas** [comment]
This issue has been fixed as we need to do the following changes as per the comment here. 
https://github.com/actions/first-interaction/issues/10#issuecomment-670968624

**Comment by FantasticFiasco** [comment]
Lol, I just did the same change on master, but reverted the commit due to your PR. Guess we came to the same conclusion regarding permissions and the interaction action.

Btw, what's the time where you are? It's morning here in Sweden and I'm typing this on my laptop balanced on my knee waiting for the bus 🤣

**Comment by MCCshreyas** [comment]
@FantasticFiasco yeah me too. I am also confused here as well because I just saw `pull_request` in workflow config and suddenly it gone, then added it back again to check and then created PR here.  But how can I test the workflow here because i don't think so it's picking up my new workflow config for this PR! 

Here its 11:35 AM in India and am at home! No outing! 😁

**Comment by FantasticFiasco** [comment]
Ah, it wasn't the same change, this was better. I removed the trigger, you changed it. Nice work!

**Comment by MCCshreyas** [comment]
Ohh man, we are commenting on the same timing as well now! Lol 😂

**Comment by FantasticFiasco** [comment]
We'll merge this one, and then I'll rebase your other PR that has the failing action, and hopefully this PR will sort the other one out. We'll try and see.

**Pull request merged**
